language:
  - cpp
compiler:
  - gcc
env:
  global:
    - secure: "hGd1dbo7f/llf+BAuR2MTFwJ9c/abzvCM48BfojAQXn68sqz/REx3p+wDvgjihnHzLths6psYob7B8idDU31dlpd8YPmEuTY+Fwi1DN4uY+DxTxdmDjY8S2zWmmLN1P3XPG0QY2T41RsqH40gNFqa9oubUhWR63/JxOSy/u+958="
script: source .travis.sh
after_success:
  - set +x
  - export GIT_COMMITTER_NAME=$GIT_NAME
  - export GIT_COMMITTER_EMAIL=$GIT_EMAIL
  - export GIT_AUTHOR_NAME=$GIT_NAME
  - export GIT_AUTHOR_EMAIL=$GIT_EMAIL
  - echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then cd ~/;            fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git clone --branch gh-pages https://github.com/$TRAVIS_REPO_SLUG doc;  fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then cd doc;           fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then cp -r $TRAVIS_BUILD_DIR/doc/_build/html/* ./; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git status;                  fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git add -f .;                  fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git commit -m "Build documents from $TRAVIS_COMMIT" . ; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git remote -v; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git push --quiet https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git gh-pages; fi
